### ISSUE TITLE
System.DllNotFoundException

### ISSUE THREAD

**Issue by ckam03** [LSXPrime/SoundFlow#1]
Just trying to run the basic usage example I'm getting

```
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'runtimes/win-x64/native/libminiaudio.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at SoundFlow.Backends.MiniAudio.Native.NativeLibraryResolver.Resolve(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at SoundFlow.Backends.MiniAudio.Native.<AllocateDeviceConfig>g____PInvoke|23_0(Capability __capabilityType_native, SampleFormat __format_native, UInt32 __channels_native, UInt32 __sampleRate_native, IntPtr __dataCallback_native)
   at SoundFlow.Backends.MiniAudio.Native.AllocateDeviceConfig(Capability capabilityType, SampleFormat format, UInt32 channels, UInt32 sampleRate, AudioCallback dataCallback)
   at SoundFlow.Backends.MiniAudio.MiniAudioEngine.InitializeAudioDevice()
   at SoundFlow.Abstracts.AudioEngine.SetupAudioThread()
   at SoundFlow.Abstracts.AudioEngine..ctor(Int32 sampleRate, Capability capability, SampleFormat sampleFormat, Int32 channels)
   at SoundFlow.Backends.MiniAudio.MiniAudioEngine..ctor(Int32 sampleRate, Capability capability, SampleFormat sampleFormat, Int32 channels)
   at audio_fun.Program.Main(String[] args) in D:\development\audio_fun\Program.cs:line 14
```

When I look inside the runtimes folder, I'm actually seeing the path of win-x64\native\win-x64\native\libminiaudio.dll so it seems like it's just looking in the wrong location but moving the dll to just win-x64\native doesn't seem to do anything.  

I tried things like this in csproj

    <None Update="bin\win-x64\native\win-x64\native\*.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

Not sure what to do at this point. Any ideas?

**Comment by LSXPrime** [comment]
Thank you for reporting this issue. I've resolved it in the latest commit and release 1.0.1. Please update your NuGet package to version 1.0.1. 

The issue was caused by a duplicated runtime path due to the following line in the library's `.csproj` file: `<PackagePath>runtimes\%(RecursiveDir)</PackagePath>`.

**Comment by ckam03** [comment]
I'm still getting the same error but I'll keep playing with it

**Comment by LSXPrime** [comment]
`ConsoleApp2.csproj: [NU1603] ConsoleApp2 depends on SoundFlow (>= 1.0.1) but SoundFlow 1.0.1 was not found. An approximate best match of SoundFlow 1.0.0 was resolved.` Are you triggering this warning during the build process? 
Locally, referencing the package directly or using the NuGet nupkg works fine. However, when installing from the NuGet server, it fails to find the package and downloads an older version instead.

The issue appears to be related to the local NuGet cache. While a complete deletion of the cache would resolve this (often referred to as 'nuking' it), a less disruptive solution is outlined below:

1. **Remove the SoundFlow dependency** from your project.
2. **Navigate to your user profile directory.** This is typically located at `%userprofile%` or `C:\Users\YourUsername\`.
3. **Rename the `.nuget` directory.**  For example, rename it to `.nuget.bak`.
4. **Re-add the SoundFlow package (version 1.0.1)** to your project and perform a build.
5. **Access the newly created `.nuget/packages` directory** within your user profile.
6. **Copy the `soundflow` package directory** from the new `.nuget/packages` location to the renamed backup directory (`.nuget.bak/packages`).
7. **Delete the newly created `.nuget` directory.**
8. **Rename the backup directory `.nuget.bak` back to `.nuget`.**

I hope this gets you up and running. If you encounter any further issues, please do not hesitate to reply here.

**Comment by rincew1nd** [comment]
I just tried to use this library in my project. But after trying to run the application, i'm getting the same error as a topic starter.
Afterwards i created an empty Console application and tried to create just an instance of MiniAudioEngine. It still fails with the same outcome.
And right now it's definitely version 1.0.1 installed in my project.

**Comment by LSXPrime** [comment]
I got the same issue and I deleted and recreated project more than 4 times and installed using 

1. `<PackageReference Include="SoundFlow" Version="1.0.1" />`
2. dotnet add package SoundFlow --version 1.0.1
3. NuGet\Install-Package SoundFlow -Version 1.0.1

but they are all the same, the project shows version 1.0.1 but after building, the file version of "SoundFlow.dll" file in your output folder will be 1.0.0 not 1.0.1, which is solved by the solution above

**Comment by rincew1nd** [comment]
It's definitely version 1.0.1. Even including full source of repo and building the library alongside with the project results in same error.
Trying to find the problem too, but i'm not that accustomed to native dll calls...
![Image](https://github.com/user-attachments/assets/a388dbb4-46e7-4bee-9375-e9bc6c5d2ff6)

**Comment by ckam03** [comment]
> `ConsoleApp2.csproj: [NU1603] ConsoleApp2 depends on SoundFlow (>= 1.0.1) but SoundFlow 1.0.1 was not found. An approximate best match of SoundFlow 1.0.0 was resolved.` Are you triggering this warning during the build process? Locally, referencing the package directly or using the NuGet nupkg works fine. However, when installing from the NuGet server, it fails to find the package and downloads an older version instead.
> 
> The issue appears to be related to the local NuGet cache. While a complete deletion of the cache would resolve this (often referred to as 'nuking' it), a less disruptive solution is outlined below:
> 
> 1. **Remove the SoundFlow dependency** from your project.
> 2. **Navigate to your user profile directory.** This is typically located at `%userprofile%` or `C:\Users\YourUsername\`.
> 3. **Rename the `.nuget` directory.**  For example, rename it to `.nuget.bak`.
> 4. **Re-add the SoundFlow package (version 1.0.1)** to your project and perform a build.
> 5. **Access the newly created `.nuget/packages` directory** within your user profile.
> 6. **Copy the `soundflow` package directory** from the new `.nuget/packages` location to the renamed backup directory (`.nuget.bak/packages`).
> 7. **Delete the newly created `.nuget` directory.**
> 8. **Rename the backup directory `.nuget.bak` back to `.nuget`.**
> 
> I hope this gets you up and running. If you encounter any further issues, please do not hesitate to reply here.
> 
> Sorry for all the troubles, my previous NuGet packages never encountered such an issue.

I don't believe I was getting that error but I tried both options anyways and I'm still getting the DLLNotFoundException. I first tried the 2nd option and then I just deleted the nuget cache by going into appData/local/nuget. I created a new project and started from scratch and still getting the DLLNotFoundException.

Stacktrace keeps pointing here:

```
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at SoundFlow.Backends.MiniAudio.Native.NativeLibraryResolver.Resolve(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at SoundFlow.Backends.MiniAudio.Native.<AllocateDeviceConfig>g____PInvoke|23_0(Capability __capabilityType_native, SampleFormat __format_native, UInt32 __channels_native, UInt32 __sampleRate_native, IntPtr __dataCallback_native)
   at SoundFlow.Backends.MiniAudio.Native.AllocateDeviceConfig(Capability capabilityType, SampleFormat format, UInt32 channels, UInt32 sampleRate, AudioCallback dataCallback)
   at SoundFlow.Backends.MiniAudio.MiniAudioEngine.InitializeAudioDevice()
   at SoundFlow.Abstracts.AudioEngine.SetupAudioThread()
   at SoundFlow.Abstracts.AudioEngine..ctor(Int32 sampleRate, Capability capability, SampleFormat sampleFormat, Int32 channels)
   at SoundFlow.Backends.MiniAudio.MiniAudioEngine..ctor(Int32 sampleRate, Capability capability, SampleFormat sampleFormat, Int32 channels)
   at Program.<Main>$(String[] args) in D:\development\Audio\Program.cs:line 8
```

**Comment by LSXPrime** [comment]
Have you tried 'dotnet nuget locals all --clear' then removing obj and bin folder then 'dotnet restore' and build again?

**Comment by LSXPrime** [comment]
> It's definitely version 1.0.1. Even including full source of the repo and building the library alongside with the project results in same error.
> Trying to find the problem too, but i'm not that accustomed to native dll calls...
> UPD. It's possible that libminiaudio requires dependency that our system lacks, i'm looking rn.
> UPD2. Yeap, mine system lacks two libraries "libgcc_s_seh-1.dll" and "libstdc++-6.dll". Can you compile the library with linked C and C++ standard libraries statically? @LSXPrime 
> ![Image](https://github.com/user-attachments/assets/a388dbb4-46e7-4bee-9375-e9bc6c5d2ff6)
> ![Image](https://github.com/user-attachments/assets/a3223589-7567-4e06-8314-1edb92acaf16)

I encountered the same issue on version 1.0.0 but after I just moved libminiaudio.dll from "runtimes/win-64/native/win-64/native/libminiaudio.dll" to "runtimes/win-64/native/libminiaudio.dll" it just worked and after I edited the nuget packing process and tested it with the new package (after I nuked my whole nuget registry to get rid of the cache) it worked, so it's not native library related issue, it's just paths issue.

**Comment by rincew1nd** [comment]
@LSXPrime i have just installed MinGW-w64 compiler on my PC (and added bin folder to PATH, so those dlls could be registered properly) and initialization was completed successfully.
So if the PC doesn't have MinGW-w64 installed (which contains those 2 DLLs), you will not be able to use these library and you will have to include those 2 DLLs in public build of your application so end user was not required to install the compiler.

**Comment by LSXPrime** [comment]
@rincew1nd I got a lot of compilers and libraries installed all over the PC that I lost count them, while the miniaudio didn't show it's necessary to have these files.
@ckam03 can you please confirm the same result? If then I will pre-bundle it tomorrow with the library.

**Comment by ckam03** [comment]
> [@rincew1nd](https://github.com/rincew1nd) I got a lot of compilers and libraries installed all over the PC that I lost count them, while the miniaudio didn't show it's necessary to have these files. [@ckam03](https://github.com/ckam03) can you please confirm the same result? If then I will pre-bundle it tomorrow with the library.

I don't know, the compiler didn't seem to make a difference for me. Still the same error

**Comment by purplechap** [comment]
I am using SoundFlow on a Mac, testing on a physical iOS device. I am also receiving the DllNotFoundException. I have tried 1.0.1 from NuGet, downloading the source code, compiling and referencing the SoundFlow.dll file directly.

Sorry I couldn't paste the text, at the moment I cannot debug my app.

![Image](https://github.com/user-attachments/assets/bbf8ab7e-8e97-403c-bde1-fd000d2ea32b)

I don't know if this makes a difference, but I did see the filename as **miniaudio** in the runtimes/iOS-arm64/native/miniaudio.framework folder when I build SoundFlow from source.

<img width="372" alt="Image" src="https://github.com/user-attachments/assets/7eeb045d-a7bd-47fd-bf00-ed39c7f290f2" />

**Comment by russkyc** [comment]
Also encountered the same issue in both android and windows. Forked the repository and tried to build the package from there but ends up with the same result.

I wanted to know if it really finds the libs in the correct path so I added a `File.Exists` check in the Resolve function of the NativeLibraryResolver and it indeed finds the dll.

![Image](https://github.com/user-attachments/assets/15413527-49d7-4e91-a824-89cb83d8f4c4)

It seems that while it does find the dll it is unabel to load said dll, I haven't tried rebuilding the actual libs but maybe this can point to the right direction.

**Comment by 4OTbIPE** [comment]
Same error in .NET9 UWP project

**Comment by LSXPrime** [comment]
Hi everyone, and thank you so much for reporting this issue and for all your patience and help in diagnosing it!  It turned out to be a rather tricky dependency problem with the native Windows DLL.

**The Good News The root cause of the `DllNotFoundException` has been identified and fixed!**
**The Bad Ones: Hopefully None**

**The Problem:** As @rincew1nd and @russkyc correctly pinpointed, the `libminiaudio.dll` was depending on MinGW runtime libraries (`libgcc_s_seh-1.dll` and `libstdc++-6.dll`, and potentially `libwinpthread-1.dll`).  These libraries are not standard Windows system DLLs and are not present on systems without MinGW installed, leading to the "DLL not found" error when the library was used on machines without the MinGW environment.

I have reconfigured the native library build process (using CMake) to **statically link** these MinGW runtime libraries directly into `libminiaudio.dll`. This makes the `libminiaudio.dll` self-contained and removes the external dependency on those separate MinGW runtime DLLs.  The resulting DLL now only depends on standard Windows system components (`KERNEL32.dll`, `msvcrt.dll`, etc.), making it truly portable across Windows machines without requiring users to install MinGW.

**Version 1.0.2 released on Nuget which include this fix.**  Please update to version 1.0.2. This should resolve the `DllNotFoundException` for most users on Windows.

@ckam03 Chris, thank you for initially reporting this and for your continued testing!  I apologize for the initial confusion with NuGet package versions and cache issues – those were likely red herrings.  The core problem, as we now know, was indeed the missing DLL dependencies, not the NuGet packaging itself.

@rincew1nd Vyacheslav, a huge thank you to you for your excellent detective work and for pinpointing the missing `libgcc_s_seh-1.dll` and `libstdc++-6.dll` dependencies!  You were absolutely correct!  Your insight was crucial in understanding the root cause and finding the right solution.

@russkyc thank you for confirming the dependency issue and for your detailed report, including the `File.Exists` check and the stack trace.  Your confirmation that copying the DLLs fixed the problem was very helpful in solidifying the diagnosis.

@purplechap Michael, thank you for reporting the issue on iOS.  I just replaced the path with the correct one (removed the "lib" from the library name)—would you mind testing again and confirm if it got fixed or not? and would you share if it's working on macOS?

@4OTbIPE Thank you for reporting the issue in UWP. While I never interacted with UWP, the static linking fix in version 1.0.2 should also resolve the dependency issue for UWP projects—would you mind testing again and confirm if it got fixed or not?


And I have updated the native build workflow to parse dependencies during the build process, and here is what each platform now has.

| Operating System | Architecture        | Dependency Type             | Dependencies                                              | Notes                                                                                                                                                  |
| :---------------- | :------------------ | :-------------------------- | :-------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------------------------------------------- |
| **macOS**         | x64, arm64          | System Libraries            | `/usr/lib/libc++.1.dylib`                               | macOS Standard C++ Library - System Library, implicitly linked.                                                                                        |
|                   |                     | System Libraries            | `/usr/lib/libSystem.B.dylib`                              | macOS System Library - Core OS services, System Library, implicitly linked.                                                                         |
| **iOS**           | arm64               | iOS Frameworks              | `AVFoundation.framework`                                 | Apple AVFoundation Framework -  Explicitly linked in CMake.                                                                                             |
|                   |                     | iOS Frameworks              | `AudioToolbox.framework`                                  | Apple AudioToolbox Framework - Explicitly linked in CMake.                                                                                              |
|                   |                     | System Frameworks/Libraries | `Foundation.framework`                                  | Apple Foundation Framework - Basic Objective-C runtime, System Framework, implicitly linked.                                                           |
|                   |                     | System Frameworks/Libraries | `CoreFoundation.framework`                              | Apple CoreFoundation Framework - Lower-level C framework, System Framework, implicitly linked.                                                          |
|                   |                     | System Libraries            | `/usr/lib/libobjc.A.dylib`                                | Objective-C Runtime Library - Needed for Objective-C++, System Library, implicitly linked.                                                            |
|                   |                     | System Libraries            | `/usr/lib/libc++.1.dylib`                                | macOS/iOS Standard C++ Library - System Library, implicitly linked.                                                                                        |
|                   |                     | System Libraries            | `/usr/lib/libSystem.B.dylib`                              | macOS/iOS System Library - Core OS services, System Library, implicitly linked.                                                                         |
| **Android**       | arm, arm64, x64     | System Libraries            | `libm.so`                                                 | Standard C Math Library - Android System Library, implicitly linked.                                                                                      |
|                   |                     | System Libraries            | `libdl.so`                                                | Dynamic Linking Loader Library - Android System Library, implicitly linked.                                                                                  |
|                   |                     | System Libraries            | `libc.so`                                                 | Standard C Library (Bionic libc) - Android System Library, implicitly linked.                                                                             |
| **Linux**         | x64, arm, arm64     | System Libraries            | `libstdc++.so.6`                                          | GNU Standard C++ Library - Linux System Library (using GCC), implicitly linked.                                                                         |
|                   |                     | System Libraries            | `libm.so.6`                                               | Standard C Math Library - Linux System Library, implicitly linked.                                                                                        |
|                   |                     | System Libraries            | `libgcc_s.so.1`                                           | GCC System Library -  Linux System Library (using GCC), implicitly linked.                                                                         |
|                   |                     | System Libraries            | `libc.so.6`                                               | Standard C Library (glibc) - Linux System Library, implicitly linked.                                                                                   |
| **Windows**       | x64, x86, arm64     | System DLLs               | `KERNEL32.dll`                                            | Core Windows System DLL - Fundamental OS services, System DLL, implicitly linked.                                                                       |
|                   |                     | System DLLs               | `msvcrt.dll`                                              | Microsoft C Runtime Library - Standard C Runtime, System DLL, implicitly linked (generally present, less critical than MinGW runtimes).               |

**Comment by purplechap** [comment]
I downloaded the source directly to test. 

**Mac Testing**

This was my initial error running the sample from the source on my Mac. I had to unblock libminiaudio.dylib. Your sample now runs. I haven't tested playing or recording yet. Worth adding to your documentation.

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'runtimes/osx-arm64/native/libminiaudio.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(runtimes/osx-arm64/native/libminiaudio.dylib, 0x0001): tried: 'runtimes/osx-arm64/native/libminiaudio.dylib' (code signature in <457AD215-C067-38E4-A248-DBC384DF9F74> '/Users/mike/Downloads/SoundFlow-master/Samples/SoundFlow.SimplePlayer/bin/Debug/net8.0/runtimes/osx-arm64/native/libminiaudio.dylib' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OSruntimes/osx-arm64/native/libminiaudio.dylib' (no such file), '/usr/lib/runtimes/osx-arm64/native/libminiaudio.dylib' (no such file, not in dyld cache), 'runtimes/osx-arm64/native/libminiaudio.dylib' (code signature in <457AD215-C067-38E4-A248-DBC384DF9F74> '/Users/mike/Downloads/SoundFlow-master/Samples/SoundFlow.SimplePlayer/bin/Debug/net8.0/runtimes/osx-arm64/native/libminiaudio.dylib' not valid for use in process: library load disallowed by system policy), '/Users/mike/Downloads/SoundFlow-master/Samples/SoundFlow.SimplePlayer/bin/Debug/net8.0/runtimes/osx-arm64/native/libminiaudio.dylib' (code signature in <457AD215-C067-38E4-A248-DBC384DF9F74> '/Users/mike/Downloads/SoundFlow-master/Samples/SoundFlow.SimplePlayer/bin/Debug/net8.0/runtimes/osx-arm64/native/libminiaudio.dylib' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/mike/Downloads/SoundFlow-master/Samples/SoundFlow.SimplePlayer/bin/Debug/net8.0/runtimes/osx-arm64/native/libminiaudio.dylib' (no such file), '/Users/mike/Downloads/SoundFlow-master/Samples/SoundFlow.SimplePlayer/bin/Debug/net8.0/runtimes/osx-arm64/native/libminiaudio.dylib' (code signature in <457AD215-C067-38E4-A248-DBC384DF9F74> '/Users/mike/Downloads/SoundFlow-master/Samples/SoundFlow.SimplePlayer/bin/Debug/net8.0/runtimes/osx-arm64/native/libminiaudio.dylib' not valid for use in process: library load disallowed by system policy)

   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at SoundFlow.Backends.MiniAudio.Native.NativeLibraryResolver.Resolve(String libraryName, Assembly assembly, Nullable`1 searchPath) in /Users/mike/Downloads/SoundFlow-master/Src/Backends/MiniAudio/Native.cs:line 29
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at SoundFlow.Backends.MiniAudio.Native.<AllocateDeviceConfig>g____PInvoke|23_0(Capability __capabilityType_native, SampleFormat __format_native, UInt32 __channels_native, UInt32 __sampleRate_native, IntPtr __dataCallback_native)
   at SoundFlow.Backends.MiniAudio.Native.AllocateDeviceConfig(Capability capabilityType, SampleFormat format, UInt32 channels, UInt32 sampleRate, AudioCallback dataCallback) in /Users/mike/Downloads/SoundFlow-master/Src/obj/Debug/net8.0/Microsoft.Interop.LibraryImportGenerator/Microsoft.Interop.LibraryImportGenerator/LibraryImports.g.cs:line 251
   at SoundFlow.Backends.MiniAudio.MiniAudioEngine.InitializeAudioDevice() in /Users/mike/Downloads/SoundFlow-master/Src/Backends/MiniAudio/MiniAudioEngine.cs:line 23
   at SoundFlow.Abstracts.AudioEngine.SetupAudioThread() in /Users/mike/Downloads/SoundFlow-master/Src/Abstracts/AudioEngine.cs:line 68
   at SoundFlow.Abstracts.AudioEngine..ctor(Int32 sampleRate, Capability capability, SampleFormat sampleFormat, Int32 channels) in /Users/mike/Downloads/SoundFlow-master/Src/Abstracts/AudioEngine.cs:line 54
   at SoundFlow.Backends.MiniAudio.MiniAudioEngine..ctor(Int32 sampleRate, Capability capability, SampleFormat sampleFormat, Int32 channels) in /Users/mike/Downloads/SoundFlow-master/Src/Backends/MiniAudio/MiniAudioEngine.cs:line 11
   at SoundFlow.SimplePlayer.Program.SetOrCreateEngine(Capability capability, Int32 sampleRate, SampleFormat sampleFormat, Int32 channels) in /Users/mike/Downloads/SoundFlow-master/Samples/SoundFlow.SimplePlayer/Program.cs:line 90
   at SoundFlow.SimplePlayer.Program.Main() in /Users/mike/Downloads/SoundFlow-master/Samples/SoundFlow.SimplePlayer/Program.cs:line 23
```
<p>
<img width="262" alt="Image" src="https://github.com/user-attachments/assets/7f8955b5-7b3a-4077-8145-271ca3a8f4d5" />
</p>

<p>
<img width="485" alt="Image" src="https://github.com/user-attachments/assets/004c4ead-0fdf-4e83-8caf-fb9d7cb41586" />
</p>

**iOS Testing**

 iOS is continuing to fail with System.DllNotFoundException: libminaudio. I am referencing Src\SoundFlow.csproj directly in my csproj.

I can't help buy wonder if the path here in Native.cs is the problem. The path in Native.cs is **runtimes/ios-arm64/native** The path showing in Rider is **runtimes/iOS-arm64/native**. These are two different folders in macOS.

            if (OperatingSystem.IsIOS())
            {
                libraryName = libraryName.Replace("lib", "");
                return RuntimeInformation.ProcessArchitecture switch
                {
                    Architecture.Arm64 => $"runtimes/ios-arm64/native/{libraryName}.framework/{libraryName}",
                    _ => throw new PlatformNotSupportedException(
                        $"Unsupported iOS architecture: {RuntimeInformation.ProcessArchitecture}")
                };
            }

**Comment by ckam03** [comment]
I don't know man, I'm still getting the same error. I created a new project, installed the package, ran the example code and it's the exact same DLLNotFoundException.  I tried deleting the local cache, deleting obj and bin folders and doing dotnet restore.

**Comment by BrycensRanch** [comment]
Yeah the library is still looking for runtimes/linux-x64/native/libminiaudio.so even though your nuget package puts the library right alongside the executable. I manually created this directory and put the library there and I get no sound and none of my outputs are detected at all


Environment

```
romvnly@Shadow-PH315-54
-----------------------
OS: Fedora Linux 43 (KDE Plasma Prerelease) x86_64
Host: Predator PH315-54 (V1.15)
Kernel: Linux 6.13.2-300.vanilla.fc41.x86_64
Uptime: 18 hours, 44 mins
Packages: 4148 (rpm), 43 (flatpak-system), 36 (flatpak-user), 16 (brew)
Shell: bash 5.2.37
Display (BOE08B3): 1920x1080 @ 144 Hz in 16" [Built-in]
DE: KDE Plasma 6.2.90
WM: KWin (Wayland)
WM Theme: WillowDarkAlt
Theme: Breeze (Dark) [Qt], Colorful-Dark-GTK [GTK3/4]
Icons: Windows11-black-dark [Qt], Windows11-black-dark [GTK3/4]
Font: SegoeUI Nerd Font (11pt, Regular) [Qt], SegoeUI Nerd Font (11pt, Thin) [GTK3/4]
Cursor: WindowsVista (48px)
Terminal: rider
CPU: 11th Gen Intel(R) Core(TM) i7-11800H (16) @ 4.60 GHz
GPU 1: NVIDIA GeForce RTX 3060 Mobile / Max-Q [Discrete]
GPU 2: Intel UHD Graphics @ 1.45 GHz [Integrated]
Memory: 25.80 GiB / 62.57 GiB (41%)
Swap: Disabled
Disk (/): 396.85 GiB / 3.64 TiB (11%) - btrfs
Battery (AP18E7M): 100% [AC Connected]
Locale: en_US.UTF-8
```

**Comment by BrycensRanch** [comment]
> Yeah the library is still looking for runtimes/linux-x64/native/libminiaudio.so even though your nuget package puts the library right alongside the executable. I manually created this directory and put the library there and I get no sound and none of my outputs are detected at all
> 
> Environment
> 
> ```
> romvnly@Shadow-PH315-54
> -----------------------
> OS: Fedora Linux 43 (KDE Plasma Prerelease) x86_64
> Host: Predator PH315-54 (V1.15)
> Kernel: Linux 6.13.2-300.vanilla.fc41.x86_64
> Uptime: 18 hours, 44 mins
> Packages: 4148 (rpm), 43 (flatpak-system), 36 (flatpak-user), 16 (brew)
> Shell: bash 5.2.37
> Display (BOE08B3): 1920x1080 @ 144 Hz in 16" [Built-in]
> DE: KDE Plasma 6.2.90
> WM: KWin (Wayland)
> WM Theme: WillowDarkAlt
> Theme: Breeze (Dark) [Qt], Colorful-Dark-GTK [GTK3/4]
> Icons: Windows11-black-dark [Qt], Windows11-black-dark [GTK3/4]
> Font: SegoeUI Nerd Font (11pt, Regular) [Qt], SegoeUI Nerd Font (11pt, Thin) [GTK3/4]
> Cursor: WindowsVista (48px)
> Terminal: rider
> CPU: 11th Gen Intel(R) Core(TM) i7-11800H (16) @ 4.60 GHz
> GPU 1: NVIDIA GeForce RTX 3060 Mobile / Max-Q [Discrete]
> GPU 2: Intel UHD Graphics @ 1.45 GHz [Integrated]
> Memory: 25.80 GiB / 62.57 GiB (41%)
> Swap: Disabled
> Disk (/): 396.85 GiB / 3.64 TiB (11%) - btrfs
> Battery (AP18E7M): 100% [AC Connected]
> Locale: en_US.UTF-8
> ```

Seems to not play any audio either on Windows.

My code:

```cs
 public static void PlaySoundAsync(Stream stream)
    {
        if (stream == null)
        {
            DebugHelper.Logger.Warning("PlaySoundAsync: stream is null");
            return;
        }

        if (!stream.CanRead)
        {
            DebugHelper.Logger.Warning("PlaySoundAsync: stream is not readable");
            return;
        }
        // if (stream.CanSeek) stream.Seek(0, SeekOrigin.Begin);


            DebugHelper.WriteLine("PlaySoundAsync: PlaySoundAsync");
            using var audioEngine = new MiniAudioEngine(44100, Capability.Playback);
            DebugHelper.WriteLine($"PlaySoundAsync: {stream.Length} bytes {stream.Position} position {stream.Position / stream.Length}");

            DebugHelper.WriteLine("PlaySoundAsync: 2");
            var player = new SoundPlayer(new StreamDataProvider(stream));
            DebugHelper.WriteLine("PlaySoundAsync: 3");
            Mixer.Master.AddComponent(player);
            DebugHelper.WriteLine("PlaySoundAsync: 4");
            foreach (var output in Mixer.Master.Outputs)
            {
                DebugHelper.WriteLine($"PlaySoundAsync Output: {output.Name}");
            }
            foreach (var output in player.Inputs)
            {
                DebugHelper.WriteLine($"PlaySoundAsync Input: {output.Name}");
            }
            player.Volume = 1;
            player.Solo = true;
            player.IsLooping = true;

            player.Play();
            DebugHelper.WriteLine("PlaySoundAsync: 5");
            player.PlaybackEnded += (s, e) =>
            {
                DebugHelper.Logger.Warning("PlaySoundAsync: PlaybackEnded");
                stream.Dispose();
                Mixer.Master.RemoveComponent(player);
            };
    }
```

Output: 

```
[16:48:12 INF] PlaySoundAsync: PlaySoundAsync
[16:48:12 INF] PlaySoundAsync: 16423 bytes 0 position 0
[16:48:12 INF] PlaySoundAsync: 2
[16:48:12 INF] PlaySoundAsync: 3
[16:48:12 INF] PlaySoundAsync: 4
[16:48:12 INF] PlaySoundAsync: 5
```

Environment 

```
Brycen@VENATOR-PH315
--------------------
OS: Windows 11 Pro x86_64
Host: Predator PH315-54 (V1.15)
Kernel: WIN32_NT 10.0.26100.2894 (24H2)
Uptime: 13 mins
Packages: 4 (scoop), 15 (choco)
Shell: CMD 10.0.26100.2454
Display (BOE08B3): 1920x1080 @ 144 Hz in 16" [Built-in]
DE: Fluent
WM: Desktop Window Manager 10.0.26100.2454
WM Theme: Custom - Blue (System: Dark, Apps: Dark)
Font: Segoe UI (12pt) [Caption / Menu / Message / Status]
Cursor: Windows Default (32px)
Terminal: Windows Terminal 1.21.3231.0
Terminal Font: Cascadia Mono (12pt)
CPU: 11th Gen Intel(R) Core(TM) i7-11800H (16) @ 2.30 GHz
GPU 1: Intel(R) UHD Graphics (128.00 MiB) [Integrated]
GPU 2: NVIDIA GeForce RTX 3060 Laptop GPU (5.86 GiB) [Discrete]
Memory: 17.24 GiB / 63.78 GiB (27%)
Swap: 0 B / 12.50 GiB (0%)
Disk (C:\): 262.79 GiB / 473.96 GiB (55%) - NTFS
Disk (D:\): 388.98 GiB / 3.64 TiB (10%) - Btrfs
Battery: 100% [AC Connected]
Locale: en-US
```
 I am using nuget release 1.0.2.

**Comment by LSXPrime** [comment]
@ckam03 @BrycensRanch  Would you please test [This Build](https://github.com/LSXAxeller/SoundFlow-Console-Demo/releases/download/V1.0.0/soundflow-demo-net8.0.zip) and post if it's playing the provided audio file (test_audio.mp3) or throwing any exceptions? Here's the [VirusTotal scan result](https://www.virustotal.com/gui/url/968cca5fbc2603b2ff809635d8312235e49703acc035462a9426dbabc3aeb542/details), I just tested it on Isolated Windows Sandbox (just installed .NET 8.0.3) and it was working all fine. If you also can test it on Windows Sandbox, that would be a bonus, providing additional valuable insight.

@BrycensRanch in Issue #2 someone reported it's working fine on his Linux Mint computer, which means the Fedora might lack a driver or a core system dependency—I will try to install a Linux distro and investigate it (using WSL if possible)—for now, could you please check that these dependencies exist on your system?
```
Run LIB_PATH="runtimes/linux-x64/native/libminiaudio.so"
Dependencies for Linux:
	linux-vdso.so.1 (0x00007ffd4ed2b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc02f021000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc02ee00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc02f1ec000)
```

The reporter in issue #2 was using version 1.0.1. In version 1.0.2, I statically linked a dependency to Linux libraries, specifically pthread, as it was required by miniaudio. Could you please verify if version 1.0.1 is still working on Linux, given that the pthread update was the only Linux-related change in version 1.0.2?

Update: @BrycensRanch  I've just pushed a commit that statically links both libgcc and libstdc++ on Linux, which should eliminate the need for compiler-specific libraries to be installed. Additionally, I've linked dl, pthread, and m according to the miniaudio documentation. Could you please test both of V1.0.1 (confirmed to be working on Linux Mint) and verify that the sample in the source works correctly when built from the source (not nuget) on Fedora?


@purplechap In the latest commit, I've configured the CMake build process to automatically sign the library and uploaded the signed dylib for macOS and iOS. Could you please build the SoundFlow Samples from source and confirm the changes? Additionally, for iOS, I've disabled runtime linking for miniaudio and linked lpthread, lm, CoreFoundation, and CoreAudio as per the miniaudio documentation and previous issues. Would you also build the C# project from source (not the native library) and test it?

**Comment by ckam03** [comment]
So your demo ran just fine and played the audio without any exceptions.

**Comment by LSXPrime** [comment]
> So your demo ran just fine and played the audio without any exceptions.

@ckam03 That means the library itself should no longer have issues on your system. Is the sample also running smoothly? [Specifically this one](https://github.com/LSXPrime/SoundFlow/tree/master/Samples/SoundFlow.SimplePlayer) - not the NuGet package, as it hasn't been updated yet.

**Comment by ckam03** [comment]
I actually didn't realize you have a sample in the repo but I just tried it out and I get the same error.

```
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'runtimes/win-x64/native/libminiaudio.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at SoundFlow.Backends.MiniAudio.Native.NativeLibraryResolver.Resolve(String libraryName, Assembly assembly, Nullable`1 searchPath) in D:\development\SoundFlow\Src\Backends\MiniAudio\Native.cs:line 29
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at SoundFlow.Backends.MiniAudio.Native.<AllocateDeviceConfig>g____PInvoke|23_0(Capability __capabilityType_native, SampleFormat __format_native, UInt32 __channels_native, UInt32 __sampleRate_native, IntPtr __dataCallback_native)
   at SoundFlow.Backends.MiniAudio.Native.AllocateDeviceConfig(Capability capabilityType, SampleFormat format, UInt32 channels, UInt32 sampleRate, AudioCallback dataCallback) in D:\development\SoundFlow\Src\obj\Debug\net8.0\Microsoft.Interop.LibraryImportGenerator\Microsoft.Interop.LibraryImportGenerator\LibraryImports.g.cs:line 251
   at SoundFlow.Backends.MiniAudio.MiniAudioEngine.InitializeAudioDevice() in D:\development\SoundFlow\Src\Backends\MiniAudio\MiniAudioEngine.cs:line 23
   at SoundFlow.Abstracts.AudioEngine.SetupAudioThread() in D:\development\SoundFlow\Src\Abstracts\AudioEngine.cs:line 68
   at SoundFlow.Abstracts.AudioEngine..ctor(Int32 sampleRate, Capability capability, SampleFormat sampleFormat, Int32 channels) in D:\development\SoundFlow\Src\Abstracts\AudioEngine.cs:line 54
   at SoundFlow.Backends.MiniAudio.MiniAudioEngine..ctor(Int32 sampleRate, Capability capability, SampleFormat sampleFormat, Int32 channels) in D:\development\SoundFlow\Src\Backends\MiniAudio\MiniAudioEngine.cs:line 11
   at SoundFlow.SimplePlayer.Program.SetOrCreateEngine(Capability capability, Int32 sampleRate, SampleFormat sampleFormat, Int32 channels) in D:\development\SoundFlow\Samples\SoundFlow.SimplePlayer\Program.cs:line 90
   at SoundFlow.SimplePlayer.Program.Main() in D:\development\SoundFlow\Samples\SoundFlow.SimplePlayer\Program.cs:line 23
```

**Comment by 4OTbIPE** [comment]
Tried 1.0.2 on NET9 UWP project - same error

**Comment by KingKestrel** [comment]
I'm also getting this error on Arch Linux.

**Comment by KingKestrel** [comment]
Okay so I moved the runtimes folder into my project's root and was able to get the project to run audio correctly. At least for now that's a fine resolution. Thank you for your work on this.

**Comment by jkodumal** [comment]
I also ran into this same issue on OS X and followed @KingKestrel's suggestion (copying the `/runtimes` folder into my project root) as a workaround. Would be good to have a permanent fix in place.

**Comment by onionhammer** [comment]
Waiting for a solution to this before embracing this library - cant wait!

Disappointed that it was closed by a bot

**Comment by LSXPrime** [comment]
@jkodumal After conducting some research, it appears that the.NET CLI has inconsistencies with the IDE, as highlighted in this GitHub issue (https://github.com/dotnet/project-system/issues/3619). The problem seems to be with the CLI itself, rather than the library, and remains unsolved on .NET side. Currently, the only workarounds are to build and manually launch from the bin path, use a launch.json file, or rely on the IDE.

@onionhammer The issue should now be resolved. The bot closed it due to inactivity, but based on other issues, it's been confirmed to be working on all listed platforms, with the exception of iOS, for which confirmation is still pending.

**Comment by onionhammer** [comment]
@LSXPrime thanks for replying.. I think this can all be accomplished with correct nuget package configuration, but OOTB, just adding your package and running (on Mac OS / ARM), does not work.

**Comment by markjamesm** [comment]
I'm running into this issue when trying to run a built version of my program. As @LSXPrime mentioned above, the app works in Rider, but given that I'd like to distribute it, it would be good to have a fix in place.

**Comment by tkefauver** [comment]
@LSXPrime 

> based on other issues, it's been confirmed to be working on all listed platforms

Still receiving the issue on Ubuntu 24.04 when running from CLI...

Seems like a handy library though thank you for sharing, would be good to get this worked out. ALC problems are the worst🤢

**Comment by LSXPrime** [comment]
Leave this open until the next commit.

**Comment by KevinL2015** [comment]
Is the GLIBC version in the UOS system too low?

![Image](https://github.com/user-attachments/assets/f635f831-c2bb-455f-89c0-38cf45cb79f5)

**Comment by LSXPrime** [comment]
@KevinL2015 It seems so, it's compiled with the `ubuntu-latest` image, which is "Ubuntu 24.04" at the moment, so it may have a more recent version of `GLIBC`.

**Comment by OlliMartin** [comment]
Same issue here, cross compiling to arm-x64 (raspi5) and directly running `dotnet run` on the pi cannot locate the `libminiaudio.so`:

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'runtimes/linux-arm64/native/libminiaudio.so' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
runtimes/linux-arm64/native/libminiaudio.so: cannot open shared object file: No such file or directory

   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at SoundFlow.Backends.MiniAudio.Native.NativeLibraryResolver.Resolve(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at SoundFlow.Backends.MiniAudio.Native.<AllocateDeviceConfig>g____PInvoke|23_0(Capability __capabilityType_native, SampleFormat __format_native, UInt32 __channels_native, UInt32 __sampleRate_native, IntPtr __dataCallback_native)
   at SoundFlow.Backends.MiniAudio.Native.<AllocateDeviceConfig>g____PInvoke|23_0(Capability __capabilityType_native, SampleFormat __format_native, UInt32 __channels_native, UInt32 __sampleRate_native, IntPtr __dataCallback_native)
   at SoundFlow.Backends.MiniAudio.Native.AllocateDeviceConfig(Capability capabilityType, SampleFormat format, UInt32 channels, UInt32 sampleRate, AudioCallback dataCallback)
```

Interestingly, it also does not work if I copy the entire runtime folder either to the solution base folder or to the project's base.

I will see if I can have a look tomorrow.

Cheers
Olli

**Comment by stevemonaco** [comment]
This issue should remain opened until fixed. SoundFlow should work with its native dependency side-by-side with the published executable as diagnosed by @mikaeldui 

As a workaround, you can move `./libminiaudio.dll` into `./runtimes/win-x64/native/` (or the appropriate runtime target for your local machine) until this is fixed. Otherwise, you cannot currently publish and release an application that uses SoundFlow.

**Comment by mikaeldui** [comment]
> This issue should remain opened until fixed. SoundFlow should work with its native dependency side-by-side with the published executable as diagnosed by [@mikaeldui](https://github.com/mikaeldui)
> 
> As a workaround, devs needing to publish an app now can move `./libminiaudio.dll` into `./runtimes/win-x64/native/` (or the appropriate runtime target for your local machine) until this is fixed. Otherwise, you cannot currently publish and release an application that uses SoundFlow.

Another workaround is to fork SoundFlow and override `private static string GetLibraryPath(string libraryName)`. Returning just "libminiaudio.so" worked for me.

**Comment by LSXPrime** [comment]
Hey, sorry for the late response on this! Been pretty busy lately.
Good news though, finally got an update out with some good new stuff and updated docs.

Update 1.0.4 is pushed, and the NuGet package is published. This *should* fix the issue now!
I've tested it on Windows and confirmed:
*   `dotnet run` works
*   `dotnet build` works
*   `dotnet publish` works
*   `dotnet publish -r win-x64 --SC` works (with and without `--SC`)

The `miniaudio.dll` loading is also fixed, whether it's in `runtimes/{rid}/native/` or right in the build root (in case of publish with rid).

This update should hopefully put an end to this issue completely! I'll leave this open for now so folks on other platforms can confirm it's good for them too.

While I finished this a week ago, I wanted to release with the new package (SoundFlow.Extensions.WebRtc.Apm) and I encountered some quirks while setting up its CI/CD

**Comment by mikaeldui** [comment]
> Hey, sorry for the late response on this! Been pretty busy lately. Good news though, finally got an update out with some good new stuff and updated docs.
> 
> Update 1.0.4 is pushed, and the NuGet package is published. This _should_ fix the issue now! I've tested it on Windows and confirmed:
> 
>     * `dotnet run` works
> 
>     * `dotnet build` works
> 
>     * `dotnet publish` works
> 
>     * `dotnet publish -r win-x64 --SC` works (with and without `--SC`)
> 
> 
> The `miniaudio.dll` loading is also fixed, whether it's in `runtimes/{rid}/native/` or right in the build root (in case of publish with rid).
> 
> This update should hopefully put an end to this issue completely! I'll leave this open for now so folks on other platforms can confirm it's good for them too.
> 
> While I finished this a week ago, I wanted to release with the new package (SoundFlow.Extensions.WebRtc.Apm) and I encountered some quirks while setting up its CI/CD

@LSXPrime  thanks for the update, but I'm still getting the error on Fedora 😞

> System.DllNotFoundException: Unable to load shared library '/runtimes/linux-x64/native/libminiaudio.so' or one of its dependencies.

**Comment by stevemonaco** [comment]
@mikaeldui Can you show your directory structure for the publish folder?

1.0.4 worked here on win-x64, like it does for LSXPrime. The library should be side-by-side with the executable. Once you start packaging or packing native files for extract, things get more complicated.

**Comment by mikaeldui** [comment]
> [@mikaeldui](https://github.com/mikaeldui) Can you show your directory structure for the publish folder?
> 
> 1.0.4 worked here on win-x64, like it does for LSXPrime. The library should be side-by-side with the executable. Once you start packaging or packing native files for extract, things get more complicated.

I created a simple console app (`MDB.SoundFlowTest`) with just SoundFlow 1.0.4 as reference:

```c-sharp
using SoundFlow.Backends.MiniAudio;
using SoundFlow.Enums;

var _audioEngine = new MiniAudioEngine(44100, Capability.Playback);
Console.WriteLine("Hello, World!");
```

Then I ran the publish command:
```bash
dotnet publish -r linux-x64 -c Release -p:Version=0.0.2 --self-contained true -p:DebugType=None -p:DebugSymbols=false -p:PublishSingleFile=true -p:PublishReadyToRun=true
```

Output:
```
Restore complete (0.8s)
  MDB.SoundFlowTest succeeded with 2 warning(s) (5.7s) → MDB.SoundFlowTest/bin/Release/net9.0/linux-x64/publish/
    ILC : warning IL3000: SoundFlow.Backends.MiniAudio.Native.NativeLibraryResolver.Resolve(String,Assembly,Nullable`1<DllImportSearchPath>): 'System.Reflection.Assembly.Location.get' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.
    /home/mikaeldui/.nuget/packages/soundflow/1.0.4/lib/net8.0/SoundFlow.dll : warning IL2104: Assembly 'SoundFlow' produced trim warnings. For more information see https://aka.ms/il2104

Build succeeded with 2 warning(s) in 6.8s
``` 

And in the `[...]/publish` folder there's just `MDB.SoundFlowTest` and `libminiaudio.so`. Running `[...]/publish/MDB.SoundFowTest` yields:

```
$ MDB.SoundFlowTest/bin/Release/net9.0/linux-x64/publish/MDB.SoundFlowTest
Unhandled exception. System.DllNotFoundException: Unable to load shared library '/runtimes/linux-x64/native/libminiaudio.so' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/runtimes/linux-x64/native/libminiaudio.so: cannot open shared object file: No such file or directory

   at System.Runtime.InteropServices.NativeLibrary.LoadLibErrorTracker.Throw(String) + 0x46
   at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String, Boolean) + 0x46
   at SoundFlow.Backends.MiniAudio.Native.NativeLibraryResolver.Resolve(String, Assembly, Nullable`1) + 0x68
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String, Assembly, Boolean, UInt32) + 0x72
   at Internal.Runtime.CompilerHelpers.InteropHelpers.FixupModuleCell(InteropHelpers.ModuleFixupCell*) + 0x80
   at Internal.Runtime.CompilerHelpers.InteropHelpers.ResolvePInvokeSlow(InteropHelpers.MethodFixupCell*) + 0x35
   at SoundFlow.Backends.MiniAudio.Native.AllocateContext() + 0x2d
   at SoundFlow.Backends.MiniAudio.MiniAudioEngine.InitializeAudioDevice() + 0x11
   at SoundFlow.Abstracts.AudioEngine..ctor(Int32, Capability, SampleFormat, Int32) + 0x16c
   at Program.<Main>$(String[] args) + 0x44
Aborted (core dumped)
```

**Comment by LSXPrime** [comment]
After testing with `dotnet publish -r win-x64 -c Release -p:Version=0.0.2 --self-contained true -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:DebugType=None -p:DebugSymbols=false`, it still worked.

A potential culprit could be missing library files. After publishing, the output folder for the working Windows build was structured like this:

```
ConsoleApp2-SF/
├── ConsoleApp2-SF.csproj
├── Program.cs
├── bin/
│   └── Release/
│       └── net8.0/
│           └── win-x64/
│               └── publish/
│                   ├── ConsoleApp2-SF.exe
│                   ├── miniaudio.dll
│                   └── webrtc-apm.dll
└── obj/
```

For the Linux environment where the issue occurs, check if `libminiaudio.so` is present in the published output directory. Also, verify the dynamic linking dependencies, which should look something like this:

```
Dependencies for Linux:
	linux-vdso.so.1 (0x0000[7](https://github.com/LSXPrime/SoundFlow/actions/runs/15086445463/job/42409568363#step:19:8)fa1e0f78000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa1e0da9000)
	libc.so.6 => /lib/x[8](https://github.com/LSXPrime/SoundFlow/actions/runs/15086445463/job/42409568363#step:19:9)6_64-linux-gnu/libc.so.6 (0x00007fa1e0a00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa1e0f7a000)
```

> Output:
```
Restore complete (0.8s)
  MDB.SoundFlowTest succeeded with 2 warning(s) (5.7s) → MDB.SoundFlowTest/bin/Release/net9.0/linux-x64/publish/
    ILC : warning IL3000: SoundFlow.Backends.MiniAudio.Native.NativeLibraryResolver.Resolve(String,Assembly,Nullable`1<DllImportSearchPath>): 'System.Reflection.Assembly.Location.get' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.
    /home/mikaeldui/.nuget/packages/soundflow/1.0.4/lib/net8.0/SoundFlow.dll : warning IL2104: Assembly 'SoundFlow' produced trim warnings. For more information see https://aka.ms/il2104

Build succeeded with 2 warning(s) in 6.8s
``` 


I did not encounter this warning during local builds. It appears that Single File Builds do not handle assembly-level location lookups (`System.Reflection.Assembly.Location`) well, but this should not be a critical issue, still I will look at it further.

**Comment by NuAoA** [comment]
I have the same issue on linux-arm64:

```bash
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'runtimes/linux-arm64/native/libminiaudio.so' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
/home/alex/PiVoiceAssistant/linux-arm64/runtimes/linux-arm64/native/libminiaudio.so: cannot open shared object file: No such file or directory
```

I've dug into it a bit. Here are some of the problems i've noticed.

1.  The `runtimes/*/native` folders are not created when using latest nuget package (I haven't validated earlier versions). However, they are created when using the source code.
2. The `linux-arm64` packages appear to be built for x86-64:
```bash
file linux-arm64/native/libminiaudio.so
linux-arm64/native/libminiaudio.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2eeb105896e993fcf24065e6dbb580960b11b236, not stripped
```

**Comment by LSXPrime** [comment]
@NuAoA Weird, seems like something's off with the build workflow. I'm doing the following on the `ubuntu-latest` image (which I'll downgrade to `ubuntu-22.04` in the next release for compatibility).

```
sudo apt-get update
sudo apt-get install -y cmake gcc g++

cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_PROCESSOR=aarch64
cmake --build . --config Release
```

Am I doing it wrong?

**Comment by LSXPrime** [comment]
@onionhammer Yeah, we are already using GitHub Runners to build the native libraries. A build, load, and exception-handling test across all platforms can be beneficial to ensure stability before release, I will try to implement this before the next release.

**Comment by Kamiperat0r** [comment]
Unfortunately, there's still an issue with **SoundFlow.Extensions.WebRtc.Apm** on Android (MAUI).

```
System.DllNotFoundException: '/data/data/*****/files/.__override__/x86_64/runtimes/android-x64/native/libwebrtc-apm.so': '(null)'
at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
at SoundFlow.Extensions.WebRtc.Apm.NativeMethods.NativeLibraryResolver.Resolve(String libraryName, Assembly assembly, Nullable`1 searchPath)
```

There is no issue with the main library.

Used version:
- SoundFlow: 1.1.1
-  SoundFlow.Extensions.WebRtc.Apm: **1.0.1** (no update available)

**Comment by LSXPrime** [comment]
@Kamiperat0r Just Fixed in version 1.0.2, please update `SoundFlow.Extensions.WebRtc.Apm` via NuGet.

**Comment by Kamiperat0r** [comment]
@LSXPrime Thank you for your quick response. With **SoundFlow.Extensions.WebRtc.Apm** 1.0.2 I now have:
```
System.DllNotFoundException: webrtc-apm 
at SoundFlow.Extensions.WebRtc.Apm.AudioProcessingModule.GetFrameSize(Int32 sampleRateHz) 
at SoundFlow.Extensions.WebRtc.Apm.Modifiers.WebRtcApmModifier..ctor(Boolean aecEnabled, Boolean aecMobileMode, Int32 aecLatencyMs, Boolean nsEnabled, NoiseSuppressionLevel nsLevel, Boolean agc1Enabled, GainControlMode agcMode, Int32 agcTargetLevel, Int32 agcCompressionGain, Boolean agcLimiter, Boolean agc2Enabled, Boolean hpfEnabled, Boolean preAmpEnabled, Single preAmpGain, Nullable`1 useMultichannelCapture, Nullable`1 useMultichannelRender, DownmixMethod downmixMethod)
```

**Comment by LSXPrime** [comment]
@Kamiperat0r That's unexpected, The resolver's Android Naming logic ([L843](https://github.com/LSXPrime/SoundFlow/blob/3c7d8d2d451abea59fc23c05a95eff8a031bd807/Extensions/SoundFlow.Extensions.WebRtc.Apm/AudioProcessingModule.cs#L843)) should return `libwebrtc-apm.so` for non-Windows platforms, not `webrtc-apm` (which is the Windows naming).

Can you attach a debugger and add some breakpoints to the Resolve method to check the final library name string passed to `NativeLibrary.Import`?

**Comment by Kamiperat0r** [comment]
@LSXPrime  I just tried debugging in release mode every way I know how: I can't debug and reproduce the issue at the same time.

Specifically, as soon as the code is compiled with the \<Optimize\>true\</Optimize\> flag, the naming logic method seems to return "**webrtc-apm**" but I can't confirm this or find out why by debugging.

And as soon as the flag is false, I can debug, but the name returned is the correct "**libwebrtc-apm.so**"...

Note that even when the name is correct, I still get a System.DllNotFoundException (see my previous message).

**Comment by LSXPrime** [comment]
@Kamiperat0r  Perhaps the paths it's searching for the library (`libwebrtc-apm.so`, either directly in the assembly root or at `/runtimes/android-arm64/native/libwebrtc-apm.so`) aren't the same on Android. If so, I should investigate this further.

**Comment by onionhammer** [comment]
> Waiting for a solution to this before embracing this library - cant wait!

Just want to say, since my first post here this issue has been improved SO MUCH. I wonder if this one can be closed now and more specific per-platform issues can be logged as they arise?

**Comment by LSXPrime** [comment]
I'm going to close this for now, as the main issue was fixed a month ago. @Kamiperat0r, can you open an independent issue and share with me a repo with a minimal procedural example of an Android application using it, for me to debug on my side?

**Comment by Kamiperat0r** [comment]
@LSXPrime Yes, I will do it in the next few days.
